import Link from "next/link";import { requireBOSAccess } from "@/lib/bos/access";
export const dynamic="force-dynamic";
const roles={OWNER:"Właściciel",ADMIN:"Administrator",MANAGER:"Menedżer",USER:"Użytkownik"} as const;
export default async function SettingsPage(){const a=await requireBOSAccess();return <><section className="p9s-head"><div><h1>Ustawienia</h1><p>Konto i wspólne środowisko platformy BOS.</p></div><span>Konto aktywne</span></section>
<section className="p9s-list">
<article><div><b>01</b><h2>Konto użytkownika</h2><p>Dane tożsamości używane podczas logowania i pracy w BOS.</p></div><dl><dt>Użytkownik</dt><dd>{a.user.displayName}</dd><dt>E-mail</dt><dd>{a.user.email}</dd></dl></article>
<article><div><b>02</b><h2>Organizacja</h2><p>Bieżący kontekst danych dla tej sesji.</p></div><dl><dt>Firma</dt><dd>{a.organization.name}</dd><dt>Rola</dt><dd>{roles[a.membership.role]}</dd></dl><Link href="/app/organization">Otwórz firmę →</Link></article>
<article><div><b>03</b><h2>Powiadomienia</h2><p>Aktualizacje produktów są dostępne wewnątrz aplikacji.</p></div><dl><dt>Kanał</dt><dd>W aplikacji</dd><dt>E-mail</dt><dd>Nieaktywny</dd></dl><Link href="/app/updates">Aktualizacje →</Link></article>
<article><div><b>04</b><h2>Bezpieczeństwo konta</h2><p>Metoda logowania zależy od sposobu utworzenia konta BOS.</p></div><dl><dt>Sesja</dt><dd>Aktywna</dd><dt>Reset hasła</dt><dd>Dostępny dla kont hasłowych</dd></dl><Link href="/forgot-password">Reset hasła →</Link></article>
</section><aside className="p9s-note"><strong>Ustawienia produktów pozostają w modułach</strong><p>Konfiguracja Wdrożeń i Awansów nie jest tutaj duplikowana.</p></aside>
<style>{`
.p9s-head{padding:18px 0 22px;border-bottom:1px solid #e8e7e2;display:flex;justify-content:space-between;align-items:flex-end}.p9s-head h1{margin:0;color:#10283b;font-family:Georgia,serif;font-size:27px;font-weight:500}.p9s-head p{margin:7px 0 0;color:#78828a;font-size:11px}.p9s-head>span{padding:6px 9px;border-radius:999px;background:#edf6ef;color:#3f7650;font-size:8px;font-weight:700}.p9s-list{margin-top:22px;background:#fff;border:1px solid #e3e2dd;border-radius:6px;overflow:hidden}.p9s-list>article{min-height:105px;padding:18px;display:grid;grid-template-columns:minmax(230px,1.2fr) minmax(260px,1fr) 120px;gap:28px;align-items:center;border-bottom:1px solid #ecebe7}.p9s-list>article:last-child{border-bottom:0}.p9s-list article>div b{color:#b18439;font-size:8px}.p9s-list h2{margin:5px 0 0;color:#294153;font-family:Georgia,serif;font-size:15px;font-weight:500}.p9s-list p{margin:5px 0 0;color:#7f898f;font-size:8px}.p9s-list dl{display:grid;grid-template-columns:75px 1fr;gap:5px 10px}.p9s-list dt{color:#8a9298;font-size:7px;font-weight:700;text-transform:uppercase}.p9s-list dd{margin:0;color:#405665;font-size:8px;font-weight:600;overflow-wrap:anywhere}.p9s-list a{justify-self:end;color:#9a722f;text-decoration:none;font-size:8px;font-weight:700}.p9s-note{margin-top:18px;padding:14px 16px;border-left:2px solid #b78a3e;background:#f7f5ef}.p9s-note strong{color:#72572a;font-size:9px}.p9s-note p{margin:5px 0 0;color:#687781;font-size:9px}@media(max-width:750px){.p9s-list>article{grid-template-columns:1fr 1fr}.p9s-list a{grid-column:2;justify-self:start}}@media(max-width:520px){.p9s-list>article{grid-template-columns:1fr;gap:14px}.p9s-list a{grid-column:1}.p9s-head{align-items:flex-start}}
`}</style></>}