import Link from "next/link";
import { requireBOSAccess } from "@/lib/bos/access";
import { listStandards,listProcesses,listClosures,getProcessProgress } from "@/lib/bos/onboardingRepository";
export const dynamic="force-dynamic";

export default async function OnboardingEntryPage(){
 const access=await requireBOSAccess();const org=access.organization.id;
 const [standards,processes,closures]=await Promise.all([listStandards(org),listProcesses(org),listClosures(org)]);
 const stages=[
  {index:"01",name:"Przygotuj",description:"Zbuduj i utrzymuj wzorzec pracy dla stanowiska.",object:"Standard Stanowiska",metric:`${standards.length} standardów`,href:"/app/onboarding/standards"},
  {index:"02",name:"Przeprowadź",description:"Uruchom wdrożenie na podstawie wybranego standardu i kontroluj postęp.",object:"Karta Postępu",metric:`${processes.length} w toku`,href:"/app/onboarding/processes"},
  {index:"03",name:"Zamknij",description:"Zweryfikuj rezultat i zachowaj zakończony proces w historii organizacji.",object:"Karta Zakończenia",metric:`${closures.length} zakończonych`,href:"/app/onboarding/closed"},
 ];
 return <><section className="bos-first-use-guide" aria-labelledby="bos-first-use-title">
   <div className="bos-first-use-head"><div><span className="bos-guidance-eyebrow">PIERWSZE UŻYCIE · 2 MINUTY</span><h2 id="bos-first-use-title">Jak działa BOS Onboarding</h2><p>Nie musisz czytać instrukcji przed rozpoczęciem. Pracuj w trzech etapach, a wskazówki pojawią się dokładnie tam, gdzie są potrzebne.</p></div><details><summary>JAK ZACZĄĆ?</summary><div className="bos-first-use-details"><p><b>Jeśli nie masz jeszcze Standardu:</b> zacznij od PRZYGOTUJ i opisz rzeczywistą pracę na stanowisku.</p><p><b>Jeśli Standard jest opublikowany:</b> przejdź do PRZEPROWADŹ i uruchom wdrożenie konkretnego pracownika.</p><p><b>Gdy proces jest kompletny:</b> ZAMKNIJ porządkuje dowody i prowadzi do decyzji człowieka.</p></div></details></div>
   <div className="bos-first-use-steps">
     <Link href="/app/onboarding/standards"><span>01</span><div><strong>PRZYGOTUJ</strong><p>Zbuduj wzorzec stanowiska: czynności, K, warunki startu i Kryterium Gotowości.</p></div><b>UTWÓRZ STANDARD →</b></Link>
     <Link href="/app/onboarding/processes"><span>02</span><div><strong>PRZEPROWADŹ</strong><p>Prowadź realną pracę przez WYJAŚNIJ → POKAŻ → RAZEM → SAM → SPRAWDŹ.</p></div><b>WDROŻENIA →</b></Link>
     <Link href="/app/onboarding/closed"><span>03</span><div><strong>ZAMKNIJ</strong><p>Sprawdź fakty względem tej samej wersji Standardu i zapisz decyzję.</p></div><b>HISTORIA →</b></Link>
   </div>
   <div className="bos-first-use-principle"><strong>Jedna zasada na start</strong><p>BOS nie pyta, czy pracownik „wydaje się gotowy”. Zapisuje to, co zostało wyjaśnione, pokazane, wykonane samodzielnie i sprawdzone.</p></div>
 </section><section className="bos-app-intro bos-onboarding-intro"><div><div className="bos-app-kicker">BOS / ONBOARDING</div><h1>BOS Onboarding</h1><p>Proces wdrożenia prowadzony od przygotowanego wzorca stanowiska, przez realizację, do kontrolowanego zamknięcia.</p></div><div className="bos-app-build-state"><span>PRODUKT</span><strong>WEB 1.0 / DANE ORGANIZACJI</strong></div></section>
 <nav className="bos-onboarding-flow" aria-label="Etapy BOS Onboarding">{stages.map(s=><Link className="bos-onboarding-flow-step" href={s.href} key={s.name}><span className="bos-onboarding-flow-index">{s.index}</span><div className="bos-onboarding-flow-copy"><strong>{s.name}</strong><small>{s.object}</small></div><span className="bos-onboarding-flow-arrow" aria-hidden="true">→</span></Link>)}</nav>
 <section className="bos-onboarding-stages"><div className="bos-dashboard-section-head"><div><span className="bos-dashboard-section-kicker">PROCES</span><h2>Trzy etapy pracy</h2></div><span className="bos-dashboard-count">wzorzec → realizacja → weryfikacja</span></div><div className="bos-onboarding-stage-list">{stages.map(s=><article className="bos-onboarding-stage-row" key={s.index}><span className="bos-onboarding-stage-number">{s.index}</span><div><h3>{s.name}</h3><p>{s.description}</p></div><div className="bos-onboarding-stage-object"><span>OBIEKT ROBOCZY</span><strong>{s.object}</strong></div><div className="bos-onboarding-stage-metric"><span>STAN ORGANIZACJI</span><strong>{s.metric}</strong></div><Link href={s.href} className="bos-onboarding-stage-open">OTWÓRZ →</Link></article>)}</div></section>
 <section className="bos-onboarding-work-grid"><div className="bos-onboarding-work"><div className="bos-dashboard-section-head"><div><span className="bos-dashboard-section-kicker">PRZYGOTUJ</span><h2>Standardy stanowisk</h2></div><Link href="/app/onboarding/standards" className="bos-onboarding-text-link">WSZYSTKIE →</Link></div><div className="bos-onboarding-table">{standards.slice(0,4).map(s=><div className="bos-onboarding-table-row" key={s.id}><strong>{s.name}</strong><span>{s.currentVersion}</span><span>{s.versions.find(v=>v.version===s.currentVersion)?.tasks.length??0} czynności</span><b>{s.status}</b></div>)}{!standards.length&&<p className="bos-global-search-empty">Brak standardów w organizacji.</p>}</div></div>
 <div className="bos-onboarding-work"><div className="bos-dashboard-section-head"><div><span className="bos-dashboard-section-kicker">PRZEPROWADŹ</span><h2>Wdrożenia w toku</h2></div><Link href="/app/onboarding/processes" className="bos-onboarding-text-link">WSZYSTKIE →</Link></div><div className="bos-onboarding-process-list">{processes.slice(0,4).map(p=>{const g=getProcessProgress(p);return <div className="bos-onboarding-process-row" key={p.id}><div><Link href={`/app/onboarding/processes/${p.id}`} className="bos-onboarding-process-direct" aria-label={`Otwórz wdrożenie: ${p.employee}`}>{p.employee}</Link><span>{standards.find(s=>s.id===p.standardId)?.name??"Standard"} · {p.standardVersion}</span></div><div className="bos-onboarding-progress" role="progressbar" aria-label={`Postęp wdrożenia ${p.employee}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={g.percent}><span style={{width:`${g.percent}%`}} /></div><b>{g.completed} / {g.total}</b><em>{g.percent}%</em></div>})}{!processes.length&&<p className="bos-global-search-empty">Brak wdrożeń w toku.</p>}</div></div></section>
 <section className="bos-onboarding-close-summary"><div><span className="bos-dashboard-section-kicker">ZAMKNIJ</span><h2>Zakończone wdrożenia</h2><p>Zamknięte procesy pozostają jako historia wykonania konkretnej wersji Standardu Stanowiska.</p></div><div className="bos-onboarding-close-number"><strong>{closures.length}</strong><span>ZAKOŃCZONYCH</span></div><Link href="/app/onboarding/closed" className="bos-onboarding-stage-open">HISTORIA →</Link></section><section className="bos-onboarding-close-summary"><div><span className="bos-dashboard-section-kicker">DANE</span><h2>Data Portability</h2><p>Eksportuj dane BOS do kanonicznego JSON lub tabel CSV do Excela i integracji ERP.</p></div><Link href="/app/onboarding/data-portability" className="bos-onboarding-stage-open">EKSPORT →</Link></section></>;
}
