import Link from "next/link";
import { requireBOSAccess } from "@/lib/bos/access";
import { listStandards,listProcesses,listClosures,getProcessProgress } from "@/lib/bos/onboardingRepository";
export const dynamic="force-dynamic";

export default async function OnboardingEntryPage(){
 const access=await requireBOSAccess();const org=access.organization.id;
 const [standards,processes,closures]=await Promise.all([listStandards(org),listProcesses(org),listClosures(org)]);
 const stages=[
  {index:"01",name:"Przygotuj",description:"Zbuduj i utrzymuj wzorzec pracy dla stanowiska.",object:"Standard Stanowiska",metric:`${standards.length} standardów`,href:"/app/onboarding/standards"},
  {index:"02",name:"Przeprowadź",description:"Uruchom wdrożenie na podstawie wybranego standardu i kontroluj postęp.",object:"Karta Postępu",metric:`${processes.length} w toku`,href:"/app/onboarding/processes"},
  {index:"03",name:"Zamknij",description:"Zweryfikuj rezultat i zachowaj zakończony proces w historii organizacji.",object:"Karta Zakończenia",metric:`${closures.length} zakończonych`,href:"/app/onboarding/closed"},
 ];
 return <><section className="bos-app-intro bos-onboarding-intro"><div><div className="bos-app-kicker">BOS / ONBOARDING</div><h1>BOS Onboarding</h1><p>Proces wdrożenia prowadzony od przygotowanego wzorca stanowiska, przez realizację, do kontrolowanego zamknięcia.</p></div><div className="bos-app-build-state"><span>PRODUKT</span><strong>WEB 1.0 / DANE ORGANIZACJI</strong></div></section>
 <nav className="bos-onboarding-flow" aria-label="Etapy BOS Onboarding">{stages.map(s=><Link className="bos-onboarding-flow-step" href={s.href} key={s.name}><span className="bos-onboarding-flow-index">{s.index}</span><div className="bos-onboarding-flow-copy"><strong>{s.name}</strong><small>{s.object}</small></div><span className="bos-onboarding-flow-arrow">→</span></Link>)}</nav>
 <section className="bos-onboarding-stages"><div className="bos-dashboard-section-head"><div><span className="bos-dashboard-section-kicker">PROCES</span><h2>Trzy etapy pracy</h2></div><span className="bos-dashboard-count">wzorzec → realizacja → weryfikacja</span></div><div className="bos-onboarding-stage-list">{stages.map(s=><article className="bos-onboarding-stage-row" key={s.index}><span className="bos-onboarding-stage-number">{s.index}</span><div><h3>{s.name}</h3><p>{s.description}</p></div><div className="bos-onboarding-stage-object"><span>OBIEKT ROBOCZY</span><strong>{s.object}</strong></div><div className="bos-onboarding-stage-metric"><span>STAN ORGANIZACJI</span><strong>{s.metric}</strong></div><Link href={s.href} className="bos-onboarding-stage-open">OTWÓRZ →</Link></article>)}</div></section>
 <section className="bos-onboarding-work-grid"><div className="bos-onboarding-work"><div className="bos-dashboard-section-head"><div><span className="bos-dashboard-section-kicker">PRZYGOTUJ</span><h2>Standardy stanowisk</h2></div><Link href="/app/onboarding/standards" className="bos-onboarding-text-link">WSZYSTKIE →</Link></div><div className="bos-onboarding-table">{standards.slice(0,4).map(s=><div className="bos-onboarding-table-row" key={s.id}><strong>{s.name}</strong><span>{s.currentVersion}</span><span>{s.versions.find(v=>v.version===s.currentVersion)?.tasks.length??0} czynności</span><b>{s.status}</b></div>)}{!standards.length&&<p className="bos-global-search-empty">Brak standardów w organizacji.</p>}</div></div>
 <div className="bos-onboarding-work"><div className="bos-dashboard-section-head"><div><span className="bos-dashboard-section-kicker">PRZEPROWADŹ</span><h2>Wdrożenia w toku</h2></div><Link href="/app/onboarding/processes" className="bos-onboarding-text-link">WSZYSTKIE →</Link></div><div className="bos-onboarding-process-list">{processes.slice(0,4).map(p=>{const g=getProcessProgress(p);return <div className="bos-onboarding-process-row" key={p.id}><div><strong>{p.employee}</strong><span>{standards.find(s=>s.id===p.standardId)?.name??"Standard"} · {p.standardVersion}</span></div><div className="bos-onboarding-progress"><span style={{width:`${g.percent}%`}} /></div><b>{g.completed} / {g.total}</b><em>{g.percent}%</em></div>})}{!processes.length&&<p className="bos-global-search-empty">Brak wdrożeń w toku.</p>}</div></div></section>
 <section className="bos-onboarding-close-summary"><div><span className="bos-dashboard-section-kicker">ZAMKNIJ</span><h2>Zakończone wdrożenia</h2><p>Zamknięte procesy pozostają jako historia wykonania konkretnej wersji Standardu Stanowiska.</p></div><div className="bos-onboarding-close-number"><strong>{closures.length}</strong><span>ZAKOŃCZONYCH</span></div><Link href="/app/onboarding/closed" className="bos-onboarding-stage-open">HISTORIA →</Link></section></>;
}