import "server-only";
import { db, hasDatabase } from "@/lib/db";
function org(id?:string){if(!id)throw new Error("organizationId is required for data portability.");return id;}
function required(){if(!hasDatabase())throw new Error("Database is required for data portability.");}
const iso=(v:unknown)=>v?new Date(v as string|Date).toISOString():"";
const clean=(rows:any[])=>rows.map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,v instanceof Date?iso(v):v])));
export type BosPortableDataset={schemaVersion:"1.1";exportedAt:string;employees:Array<Record<string,unknown>>;standards:Array<Record<string,unknown>>;standardVersions:Array<Record<string,unknown>>;standardTasks:Array<Record<string,unknown>>;startRequirements:Array<Record<string,unknown>>;readinessCriteria:Array<Record<string,unknown>>;onboardingProcesses:Array<Record<string,unknown>>;onboardingClosures:Array<Record<string,unknown>>;promotionProcesses:Array<Record<string,unknown>>;promotionProcessTasks:Array<Record<string,unknown>>;promotionAssessments:Array<Record<string,unknown>>;promotionEvidenceReferences:Array<Record<string,unknown>>;promotionDeploymentProgress:Array<Record<string,unknown>>;promotionReadinessChecks:Array<Record<string,unknown>>;promotionTransitionItems:Array<Record<string,unknown>>;promotionDecisions:Array<Record<string,unknown>>;promotionClosureEvents:Array<Record<string,unknown>>;};
export async function buildPortableDataset(organizationId?:string):Promise<BosPortableDataset>{
 required();const sql=db();const organization=org(organizationId);
 const [employees,standards,versions,tasks,startRequirements,readinessCriteria,onboardingProcesses,onboardingClosures,promotionProcesses,promotionProcessTasks,promotionAssessments,promotionEvidenceReferences,promotionDeploymentProgress,promotionReadinessChecks,promotionTransitionItems,promotionDecisions,promotionClosureEvents]=await Promise.all([
  sql`SELECT e.id,e.employee_number,e.first_name,e.last_name,COALESCE((SELECT c.to_role_snapshot FROM promotion_closure_events c WHERE c.organization_id=e.organization_id AND c.employee_id=e.id AND c.closure_kind='READY' ORDER BY c.closed_at DESC,c.closure_sequence DESC LIMIT 1),e.position) position,e.department,e.status,e.linked_user_id,e.created_at,e.updated_at FROM employees e WHERE e.organization_id=${organization} ORDER BY e.last_name,e.first_name,e.id`,
  sql`SELECT id,product_id,name,area,status,current_version_id,created_at,updated_at FROM standards WHERE organization_id=${organization} ORDER BY name,id`,
  sql`SELECT id,standard_id,version_number,version_label,status,change_note,created_by_user_id,published_by_user_id,published_at,created_at FROM standard_versions WHERE organization_id=${organization} ORDER BY standard_id,version_number`,
  sql`SELECT id,standard_version_id,position,name,execution,ready_when,hint,is_critical FROM standard_tasks WHERE organization_id=${organization} ORDER BY standard_version_id,position`,
  sql`SELECT id,standard_version_id,position,category,requirement FROM standard_start_requirements WHERE organization_id=${organization} ORDER BY standard_version_id,position`,
  sql`SELECT id,standard_version_id,position,criterion,verification_method,verification_method_other FROM standard_readiness_criteria WHERE organization_id=${organization} ORDER BY standard_version_id,position`,
  sql`SELECT id,product_id,employee_id,employee_name_snapshot,standard_id,standard_version_id,owner_user_id,trainer_user_id,evaluator_user_id,buddy_user_id,status,started_on,target_on,closed_at,created_at,updated_at FROM onboarding_processes WHERE organization_id=${organization} ORDER BY created_at,id`,
  sql`SELECT id,onboarding_process_id,standard_id,standard_version_id,employee_name_snapshot,decision,verified_by_user_id,summary,recommendations,decision_sequence,verified_at FROM onboarding_closures WHERE organization_id=${organization} ORDER BY onboarding_process_id,decision_sequence`,
  sql`SELECT pp.id,pp.product_id,pp.employee_id,pp.employee_name_snapshot,pp.from_role,pp.to_role,pp.change_type,pp.owner_user_id,bos_promotion_lifecycle_state(pp.id) status,pp.effective_on,pp.started_on,pp.created_by_user_id,pp.standard_id,pp.standard_version_id,pp.created_at,COALESCE((SELECT c.closed_at FROM promotion_closure_events c WHERE c.organization_id=pp.organization_id AND c.promotion_process_id=pp.id ORDER BY c.closure_sequence DESC LIMIT 1),pp.updated_at) updated_at FROM promotion_processes pp WHERE pp.organization_id=${organization} ORDER BY pp.created_at,pp.id`,
  sql`SELECT id,promotion_process_id,standard_task_id,position_snapshot,name_snapshot,is_critical_snapshot,created_at FROM promotion_process_tasks WHERE organization_id=${organization} ORDER BY promotion_process_id,position_snapshot`,
  sql`SELECT id,promotion_process_id,promotion_process_task_id,initial_assessment,evidence_note,assessed_by_user_id,assessed_at,verification_result,verification_by_user_id,verification_at,verification_note,created_at,updated_at FROM promotion_assessments WHERE organization_id=${organization} ORDER BY promotion_process_id,created_at,id`,
  sql`SELECT id,promotion_process_id,promotion_assessment_id,source_type,source_process_id,source_closure_id,source_standard_id,source_standard_version_id,source_standard_task_id,evidence_type,source_result_snapshot,source_description_snapshot,source_date,added_by_user_id,created_at FROM promotion_evidence_references WHERE organization_id=${organization} ORDER BY promotion_process_id,created_at,id`,
  sql`SELECT id,promotion_process_id,promotion_assessment_id,explained_at,explained_by_user_id,shown_at,shown_by_user_id,together_at,together_by_user_id,solo_at,solo_by_user_id,checked_at,checked_by_user_id,note,created_at,updated_at FROM promotion_deployment_progress WHERE organization_id=${organization} ORDER BY promotion_process_id,created_at,id`,
  sql`SELECT id,promotion_process_id,readiness_criterion_id,criterion_snapshot,verification_method_snapshot,verification_method_other_snapshot,result,checked_by_user_id,checked_at,note,created_at,updated_at FROM promotion_readiness_checks WHERE organization_id=${organization} ORDER BY promotion_process_id,created_at,id`,
  sql`SELECT id,promotion_process_id,position,item,disposition,confirmation,evidence_note,confirmed_by_user_id,confirmed_at,created_by_user_id,created_at,updated_at FROM promotion_transition_items WHERE organization_id=${organization} ORDER BY promotion_process_id,position`,
  sql`SELECT id,promotion_process_id,decision,decision_sequence,decided_by_user_id,decided_at,note,standard_pass,process_pass,entry_pass,deployment_pass,k_pass,readiness_pass,transition_pass,created_at FROM promotion_decisions WHERE organization_id=${organization} ORDER BY promotion_process_id,decision_sequence`,
  sql`SELECT id,promotion_process_id,promotion_decision_id,closure_kind,closure_sequence,employee_id,employee_name_snapshot,from_role_snapshot,to_role_snapshot,change_type_snapshot,standard_id,standard_version_id,closed_by_user_id,closed_at,note,created_at FROM promotion_closure_events WHERE organization_id=${organization} ORDER BY promotion_process_id,closure_sequence`
 ]);
 return {schemaVersion:"1.1",exportedAt:new Date().toISOString(),employees:clean(employees),standards:clean(standards),standardVersions:clean(versions),standardTasks:clean(tasks),startRequirements:clean(startRequirements),readinessCriteria:clean(readinessCriteria),onboardingProcesses:clean(onboardingProcesses),onboardingClosures:clean(onboardingClosures),promotionProcesses:clean(promotionProcesses),promotionProcessTasks:clean(promotionProcessTasks),promotionAssessments:clean(promotionAssessments),promotionEvidenceReferences:clean(promotionEvidenceReferences),promotionDeploymentProgress:clean(promotionDeploymentProgress),promotionReadinessChecks:clean(promotionReadinessChecks),promotionTransitionItems:clean(promotionTransitionItems),promotionDecisions:clean(promotionDecisions),promotionClosureEvents:clean(promotionClosureEvents)};
}
const csvCell=(value:unknown)=>{const raw=value==null?"":typeof value==="object"?JSON.stringify(value):String(value);return /[",\n\r;]/.test(raw)?`"${raw.replace(/"/g,'""')}"`:raw;};
export function recordsToCsv(records:Array<Record<string,unknown>>){if(!records.length)return "";const headers=Object.keys(records[0]);return [headers.join(","),...records.map(row=>headers.map(h=>csvCell(row[h])).join(","))].join("\r\n");}
export function portableDatasetToCsvFiles(data:BosPortableDataset){return {"employees.csv":recordsToCsv(data.employees),"standards.csv":recordsToCsv(data.standards),"standard_versions.csv":recordsToCsv(data.standardVersions),"standard_tasks.csv":recordsToCsv(data.standardTasks),"start_requirements.csv":recordsToCsv(data.startRequirements),"readiness_criteria.csv":recordsToCsv(data.readinessCriteria),"onboarding_processes.csv":recordsToCsv(data.onboardingProcesses),"onboarding_closures.csv":recordsToCsv(data.onboardingClosures),"promotion_processes.csv":recordsToCsv(data.promotionProcesses),"promotion_process_tasks.csv":recordsToCsv(data.promotionProcessTasks),"promotion_assessments.csv":recordsToCsv(data.promotionAssessments),"promotion_evidence_references.csv":recordsToCsv(data.promotionEvidenceReferences),"promotion_deployment_progress.csv":recordsToCsv(data.promotionDeploymentProgress),"promotion_readiness_checks.csv":recordsToCsv(data.promotionReadinessChecks),"promotion_transition_items.csv":recordsToCsv(data.promotionTransitionItems),"promotion_decisions.csv":recordsToCsv(data.promotionDecisions),"promotion_closure_events.csv":recordsToCsv(data.promotionClosureEvents)};}
