"use client";

import { useEffect, useRef, useState } from "react";

export type MicrophoneState = "idle" | "requesting" | "active" | "denied" | "unsupported";
type MicrophoneControlProps={onStateChange?:(state:MicrophoneState)=>void;onStreamChange?:(stream:MediaStream|null)=>void};
type VoiceInformationState="unknown"|"presented"|"acknowledged";
type VoiceInformationRecord={state:"acknowledged";version:1;acknowledgedAt:string};
const VOICE_NOTICE_KEY="bos.voice.firstUseNotice.v1";
function readVoiceInformationState():VoiceInformationState{try{const raw=localStorage.getItem(VOICE_NOTICE_KEY);if(!raw)return"unknown";if(raw==="acknowledged")return"acknowledged";const r=JSON.parse(raw) as Partial<VoiceInformationRecord>;return r.state==="acknowledged"&&r.version===1?"acknowledged":"unknown";}catch{return"unknown";}}

export default function MicrophoneControl({onStateChange,onStreamChange}:MicrophoneControlProps){
 const [state,setState]=useState<MicrophoneState>("idle");const [showNotice,setShowNotice]=useState(false);const [showPrivacy,setShowPrivacy]=useState(false);const [informationState,setInformationState]=useState<VoiceInformationState>("unknown");
 const streamRef=useRef<MediaStream|null>(null);const noticeRef=useRef<HTMLDivElement|null>(null);const previousFocusRef=useRef<HTMLElement|null>(null);
 function updateState(next:MicrophoneState){setState(next);onStateChange?.(next);}
 function stopMicrophone(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;onStreamChange?.(null);updateState("idle");}
 async function startMicrophone(){if(!navigator.mediaDevices?.getUserMedia){updateState("unsupported");return;}updateState("requesting");try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});streamRef.current=stream;onStreamChange?.(stream);updateState("active");}catch(error){const denied=error instanceof DOMException&&(error.name==="NotAllowedError"||error.name==="SecurityError");onStreamChange?.(null);updateState(denied?"denied":"idle");}}
 async function toggleMicrophone(){if(state==="active"){stopMicrophone();return;}const s=readVoiceInformationState();setInformationState(s);if(s!=="acknowledged"){setInformationState("presented");setShowNotice(true);return;}await startMicrophone();}
 async function acceptNotice(){const r:VoiceInformationRecord={state:"acknowledged",version:1,acknowledgedAt:new Date().toISOString()};try{localStorage.setItem(VOICE_NOTICE_KEY,JSON.stringify(r));}catch{}setInformationState("acknowledged");setShowNotice(false);setShowPrivacy(false);await startMicrophone();}
 function closeNotice(){setShowNotice(false);setShowPrivacy(false);}
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;onStreamChange?.(null);},[onStreamChange]);
 useEffect(()=>{if(!showNotice)return;previousFocusRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const dialog=noticeRef.current;dialog?.querySelector<HTMLElement>("button, [href], input, select, textarea, [tabindex]:not([tabindex='-1'])")?.focus();function key(e:KeyboardEvent){if(e.key==="Escape"){e.preventDefault();closeNotice();return;}if(e.key!=="Tab"||!dialog)return;const nodes=Array.from(dialog.querySelectorAll<HTMLElement>("button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex='-1'])"));if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previousFocusRef.current?.focus();};},[showNotice]);
 const label=state==="active"?"Wyłącz mikrofon":state==="requesting"?"Oczekiwanie na dostęp do mikrofonu":"Włącz mikrofon";
 return <div className="bos-microphone-control"><button className={`bos-microphone-button bos-microphone-button-${state}`} type="button" onClick={toggleMicrophone} disabled={state==="requesting"} aria-label={label} aria-pressed={state==="active"} title={label}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 14.5a4 4 0 0 0 4-4V6a4 4 0 1 0-8 0v4.5a4 4 0 0 0 4 4Zm-2-8.5a2 2 0 1 1 4 0v4.5a2 2 0 1 1-4 0V6Zm8 4a1 1 0 0 1 2 0v.5a8 8 0 0 1-7 7.94V21h3a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h3v-2.56A8 8 0 0 1 4 10.5V10a1 1 0 1 1 2 0v.5a6 6 0 0 0 12 0V10Z"/></svg>{state==="active"&&<span className="bos-microphone-live-dot" aria-hidden="true"/>}</button>
 {(state==="denied"||state==="unsupported")&&<span className="bos-microphone-error" role="status">{state==="denied"?"Brak dostępu do mikrofonu.":"Mikrofon nie jest obsługiwany w tej przeglądarce."}</span>}
 {showNotice&&<div className="bos-voice-notice-backdrop" role="presentation"><div ref={noticeRef} className="bos-voice-notice" role="dialog" aria-modal="true" aria-labelledby="bos-voice-notice-title" aria-describedby="bos-voice-notice-description" data-information-state={informationState}><span className="bos-voice-notice-label">BOS VOICE · AI</span>
 {!showPrivacy?<><h3 id="bos-voice-notice-title">Rozmowa głosowa z systemem AI</h3><p id="bos-voice-notice-description">Aby prowadzić rozmowę głosową, dźwięk z mikrofonu jest przetwarzany w celu rozpoznania wypowiedzi i wygenerowania odpowiedzi.</p><div className="bos-voice-microphone-disclosure" role="note" aria-label="Informacja o mikrofonie"><strong>Mikrofon zostanie uruchomiony dopiero po Twoim działaniu.</strong><p>Po wybraniu „Uruchom Voice” BOS poprosi przeglądarkę o dostęp do mikrofonu. Przeglądarka może wyświetlić własne, osobne pytanie o zgodę.</p><p>Gdy mikrofon jest aktywny, jego stan jest widoczny w interfejsie. Możesz go wyłączyć w dowolnym momencie przyciskiem mikrofonu albo odebrać dostęp w ustawieniach przeglądarki.</p></div><button type="button" className="bos-voice-privacy-link" onClick={()=>setShowPrivacy(true)}>Jak przetwarzamy dane?</button></>:<><h3 id="bos-voice-notice-title">Prywatność BOS Voice</h3><div id="bos-voice-notice-description" className="bos-voice-privacy-details"><p><strong>Zakres.</strong> Voice przetwarza dźwięk z mikrofonu oraz treść rozmowy potrzebną do działania asystenta.</p><p><strong>Cel.</strong> Dane są używane do rozpoznania wypowiedzi, utrzymania kontekstu rozmowy i wygenerowania odpowiedzi AI.</p><p><strong>Dostęp BOS.</strong> W obecnej wersji Voice nie otrzymuje prawa do samodzielnego zapisu ani modyfikacji danych BOS.</p><p><strong>Dostawca AI.</strong> Przetwarzanie rozmowy głosowej korzysta z usługi OpenAI Realtime API.</p><p className="bos-voice-privacy-pending">Szczegółowe informacje o administratorze danych, podstawie prawnej, retencji, odbiorcach, transferach i prawach użytkownika zostaną uzupełnione w polityce prywatności przed wdrożeniem produkcyjnym.</p></div><button type="button" className="bos-voice-privacy-link" onClick={()=>setShowPrivacy(false)}>Wróć do informacji o Voice</button></>}
 <div className="bos-voice-notice-actions"><button type="button" className="bos-voice-notice-cancel" onClick={closeNotice}>Anuluj</button><button type="button" className="bos-voice-notice-start" onClick={acceptNotice}>Uruchom Voice</button></div></div></div>}</div>;
}
